### ISSUE TITLE
Sciter is missing

### ISSUE THREAD

**Issue by EdorianDark** [areweguiyet/areweguiyet#11]
There are [official bindings](https://github.com/sciter-sdk/rust-sciter) to [sciter](https://sciter.com/).
Sciter enables to write a gui with web tec, like Elektron.

**Comment by serak** [comment]
Yes exactly why is the most amazing gui binding missing?

**Comment by shivshank** [comment]
Thanks. Added. Let me know if there's any issues! Will close shortly.
