### ISSUE TITLE
Page should not require the browser to fill the entire screen in order to be readable

### ISSUE THREAD

**Issue by jansol** [areweguiyet/areweguiyet#12]
So the page apparently uses flexbox for a pleasant resolution independent layout. Nice. Ironically the main body of the page has a fixed width of 1200px, defeating the point of using flexbox in the first place and causing the text to get cut off on my laptop. Unless I effectively fullscreen my browser, that is. I get that modern web design is meant to "encourage" people to interact more with their browsers, but for people stuck in their windowed ways this is quite bothersome.
<br/>
<br/>
<br/>
<sub>/s, but the rant still applies</sub>

**Comment by shivshank** [comment]
Thanks for the feedback, this was an oversight, really, although I don't intend to make the site full screen app style on wide screens.

Attempted to make more small screen/window friendly. Looking good at 800px wide should still basically be a requirement for being online... But needs a 'lil more work.

**Comment by jansol** [comment]
Another decent solution would be to use different styling for wide and narrow screens using [media rules](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp). Maybe.

**Comment by shivshank** [comment]
Let me know if my most recent change helps, http://areweguiyet.com/. I still want to uncenter things on wide screen and fix tag formatting when I get a chance, but added another media query to attempt to improve things for the time being.
