### ISSUE TITLE
areweguiyet https cert errors

### ISSUE THREAD

**Issue by raphlinus** [areweguiyet/areweguiyet#13]
I'm not sure who best to report this to, so filing as an issue here. Feel free to route and close.

If I open https://areweguiyet.com/ I get a cert error, saying it's a *.github.com cert (and also including *.github.io). This is probably a very simple misconfiguration.

The http still works, but I always try to prefer https.

**Comment by pythoneer** [comment]
Thanks for opening the ticked! I'll have a look.

**Comment by shivshank** [comment]
@pythoneer hey I looked into this last night and it looks like our DNS A record for the website is set to 192.30.252.153, and for https to work GitHub requires people to use one of

    185.199.108.153
    185.199.109.153
    185.199.110.153
    185.199.111.153

https://help.github.com/en/articles/troubleshooting-custom-domains#https-errors

(and then we can even enforce https on Github pages apparently! 😉 )

**Comment by pythoneer** [comment]
@shivshank  I'll change that as soon as i am at home. Have the ip's changed? I am just wondering – in my memory this has worked in the past.

**Comment by pythoneer** [comment]
should be fixed now.
