### ISSUE TITLE
Filter to hide discontinued projects

### ISSUE THREAD

**Issue by nmoreaud** [areweguiyet/areweguiyet#161]

**Comment by madsmtm** [comment]
Is there a discontinued project on the site? If so, we should just remove it.

**Comment by nmoreaud** [comment]
Yep, the Druid project has been discontinued

**Comment by megabyte6** [comment]
As nice of a project as conrod-core seems, its maintainer has stepped down (as shown on [the crate](https://crates.io/crates/conrod-core) and [the repo](https://github.com/pistondevelopers/conrod)) and there hasn't been any activity on the project in over 2 years.

**Comment by megabyte6** [comment]
[Vizia](https://crates.io/crates/vizia) has no description (only a "Coming soon..."), a single release (v0.1.0), no source, and hasn't been updated in 3 years.

**Comment by madsmtm** [comment]
Thanks for the input both of you, have filed https://github.com/areweguiyet/areweguiyet/pull/168 to fix this.

**Comment by xStrom** [comment]
GTK3 bindings have also been discontinued. The [repo has been archived](https://github.com/gtk-rs/gtk3-rs) since Mar 4, 2024 and you can't use it with the latest GTK core libraries.

**Comment by madsmtm** [comment]
Not gonna remove `gtk` yet, it's [still depended on by major players](https://lib.rs/crates/gtk/rev), and has more downloads than `gtk4`.

**Comment by megabyte6** [comment]
The repository for [rstk](https://codeberg.org/peterlane/rstk/) has been archived as of February 1, 2024. The [crate](https://crates.io/crates/rstk) also doesn't have many downloads.

**Comment by megabyte6** [comment]
The repository for [rust-qt-binding-generator](https://invent.kde.org/sdk/rust-qt-binding-generator) has also been archived. There also hasn't been an update to the [crate](https://crates.io/crates/rust-qt-binding-generator) in 3 years.

**Comment by madsmtm** [comment]
Done in https://github.com/areweguiyet/areweguiyet/pull/170.
