### ISSUE TITLE
Redirect Domain

### ISSUE THREAD

**Issue by pythoneer** [areweguiyet/areweguiyet#3]
redirect the current domain of "http://areweguiyet.com/" to the new website for launch

**Comment by shivshank** [comment]
I just tried to add it but I currently get this error:

https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken

It looks like the CNAME in the old repo has to be removed first.

**Comment by pythoneer** [comment]
i have changed the cname in my old repo – i guess we could try again. But i think a have not enough rights to change it by myself (i don't know where to put the CNAME file manually) because i have no settings panel.

**Comment by shivshank** [comment]
Awesome; done! The link should work now. I found a setting for it, but for what it's worth it looks like the setting just creates a commit automatically:

https://github.com/areweguiyet/areweguiyet/commit/2eac640eda32401ada61e282c1b154e46b627c7c

**Comment by pythoneer** [comment]
nice! i think we could close this now

btw: can we have some place for chat? communication through GH issues is a bit out of place i think. I had a [discord channel](https://discord.gg/RE6aNAu) from my old page but you can suggest something else if you like. I am not the biggest fan of discord but it works and i don't have strong feelings about it anyway but i have some channels there i regularly watch so i watching it anyways.
