### ISSUE TITLE
Catch up with progress / watch for new emerging projects

### ISSUE THREAD

**Issue by pythoneer** [areweguiyet/areweguiyet#31]
https://rust-qt.github.io/

https://github.com/areweguiyet/areweguiyet/pull/30 ( https://github.com/MoAlyousef/fltk-rs )

https://github.com/bodil/vgtk

https://github.com/lykhonis/terramach

**Comment by madsmtm** [comment]
Triage:
- rust-qt seems dead (last commit May 18, 2021)
- fltk-rs is already linked to
- vgtk is already linked to
- terramach seems dead (last commit Apr 1, 2020)

So I'll consider this done
