### ISSUE TITLE
SSL connection error

### ISSUE THREAD

**Issue by Aloso** [areweguiyet/areweguiyet#37]
Currently both Firefox and Chrome reject the SSL certificate when trying to connect to [`www.areweguiyet.com`](https://www.areweguiyet.com). If I remove the `www` from the URL, it works.

**Comment by dxenonb** [comment]
After a bunch of testing, referring to `arewegameyet.rs` I was at a dead end. Wrote up some notes here, but I believe I understand the issue now.

We can do this:
https://stackoverflow.com/questions/54817253/github-pages-https-www-redirect

Which will cause Github to serve a 301 for the subdomain, which will hopefully also cause Github to serve the right cert.

What's really crazy is Are We Game Yet's DNS situation, which was really throwing me - the main points to the GithubPages IP, while the subdomain points to the GameDev WG site via CNAME. Yet, when you request the subdomain, the IP will ultimately just resolve to GithubPages, which sees the `Host` header in the HTTP request, which serves up the 301. 😓 At least, that's what I think is happening...

**Comment by dxenonb** [comment]
It seems it is redirecting now, treating `www` as the main. I'll switch it back tomorrow if everything looks OK. Considering this resolved.
