### ISSUE TITLE
Consider adding "moxie" to list of libraries

### ISSUE THREAD

**Issue by andoks** [areweguiyet/areweguiyet#39]
I saw [this talk](https://youtu.be/tmM756XZt20) on YouTube, presenting the (very alpha) [moxie library](https://github.com/anp/moxie). It might belong in the list of gui libraries, although it seems like it still is mostly the original author working on it.

**Comment by madsmtm** [comment]
It seems like the last activity in moxie was on October 31, 2021, so I assume the project is dead.

If it becomes active again, feel free to reopen
