### ISSUE TITLE
How should Approaches section work?

### ISSUE THREAD

**Issue by shivshank** [areweguiyet/areweguiyet#4]
The original plan for this repo in May 2018 was to simply collect notes on how one *might* approach a GUI in Rust, and then catalog the benefits and drawbacks of each approach.

**Should we still attempt to do this?** Or should it be relegated to blog/news posts?

It may be beneficial to have a central community hub for recording developments in a chapter by chapter "book" form. The "book" would describe different approaches without "choosing" one. 

The book would evolve over the coming months and years as people learn what works, what doesn't, what's fun, and what's not. It would ideally contain lots of working code and reference a lot of active projects as examples.

**Comment by dxenonb** [comment]
I am imagining using mdbook for this, if this ever becomes a thing.

Audience: GUI developers.

Content: contains no reference to existing frameworks.

Possible hasty outline for inspiration:

 - Introduction
 - Functional Specification
  - Brief History of GUIs
  - Form Factors Today (e.g. something like Mobile/Tablet/Kiosk/Web/Desktop)
  - Interaction and Accessibility
  - Compliance and Industry Requirements
  - Design Guidelines (e.g. catalog things like the Material Design Specification)
 - Technical Specification
  - Building Native Frameworks (e.g. options involved in implementing custom rendere )
  - Windowing and Event Management (provide an in depth comparison on how every platform manages windows)
  - Text Rendering (introduction to layout, rendering, etc)
 - API Design Approaches
  - Brief Introduction and Overview
  - Layout and Rendering
  - User Interaction and Event Management
  - Case Studies
    - The DOM
    - ... page per popular framework (React, Flutter, Windows API, Swift UI) with discussion of advantages and trade offs

Maybe I'll get to this in 2025?
