### ISSUE TITLE
Restart for 2019

### ISSUE THREAD

**Issue by pythoneer** [areweguiyet/areweguiyet#6]
I am currently [preparing a Blogpost](https://github.com/pythoneer/areweguiyet/blob/master/rust2019.md) for the Rust2019 community blog call out. Things have a little died out – but we should consider a restart :)

**Comment by shivshank** [comment]
Yes, haha! This has been on my mind.

I also enjoyed your post. I think you hit all the best points. Having *at least one* really great Rust GUI framework would be a game changer for the language.

Let me know if you have other thoughts!

**Comment by shivshank** [comment]
@pythoneer Almost ready!

I am using clap for making the CLI. Right now it only has the `publish` command, which generates the HTML. The work flow looks like this:

```
git clone [areweguiyet git url]
cd areweguiyet/cli
cargo run -- publish
```

**The next step** is to add a command for adding a new crate, to help guarantee that the `ecosystem.json` is correct. The CLI will also display what information that is already available on crates.io and make sure that the AreWeGuiYet repo doesn't duplicate information from crates.io.

I broke the alphabetical sorting on the main web page; I will fix that. After finishing the CLI, I want to add a search bar and filtering by tags to the main webpage.

I am currently working off of a fork: https://github.com/shivshank/areweguiyet. I will open a PR here when I finish the CLI.

**Comment by shivshank** [comment]
Opened a PR, #7, which adds the `framework` command for adding frameworks!
