### ISSUE TITLE
Gtk link deprecated

### ISSUE THREAD

**Issue by ramones156** [areweguiyet/areweguiyet#64]
Gtk link currently goes to https://github.com/gtk-rs/gtk which is deprecated. New link should be https://github.com/gtk-rs/gtk-rs

**Comment by dxenonb** [comment]
It looks to me like the links are currently redirecting where they need to (using values provided from crates.io)

In the ecosystem.json we should maybe update the docs.rs link for GTK (since it is a redirect)

If someone can confirm any issues that would be great
