### ISSUE TITLE
Neon Bindings + Electron

### ISSUE THREAD

**Issue by xamgore** [areweguiyet/areweguiyet#67]
1password has recently [released a new Linux client](https://blog.1password.com/welcoming-linux-to-the-1password-family/) written with Electron (React.js) & Neon Bindings. Looks like it can be added to the list.

**Comment by fhennig** [comment]
@xamgore this is just an application, and it has nothing to do with Rust either if I'm seeing that right?

**Comment by xamgore** [comment]
I mean, there is a description of the tech stack in their blog.

**Comment by madsmtm** [comment]
> the user interface (UI) is written in React with Neon bindings to the Rust backend

It seems like they only use Rust for processing, not for the actual UI - so while interesting, not really that useful to people looking to do so (which is what this website caters to).
