### ISSUE TITLE
Add news item for azul 1.0.0-alpha release?

### ISSUE THREAD

**Issue by fschutt** [areweguiyet/areweguiyet#73]
Hi,

a couple of days ago I released the first version of azul: https://github.com/fschutt/azul/releases/tag/1.0.0-alpha1

Not sure if this is news-worthy, just a thought that you might want to add it to the website

Thanks

**Comment by dxenonb** [comment]
Excited to see your continued work on azul!

Is anyone else able to weigh in on inclusion of this?

I am unsure if we should generally include release posts or not... @fschutt are you writing on azul anywhere else like a blog, or have retrospectives on development? I think that is more objectively a better fit for inclusion, but I can be swayed on this!

Apologies for the delay on getting to this (now 6+ months ago). If you and others would still like to see 1.0.0 or another release included, I am happy to add it!

**Comment by fschutt** [comment]
Yeah I think I'll wait until the 1.0 release. Yes, azul isn't dead, I've actually used it at work. But I need to finish the ListView and TreeView widget before I can really show it off.

**Comment by madsmtm** [comment]
I agree with @dxenonb that release announcements are not really that interesting - while it's nice to know that progress is being made, I think it's more valuable that the news feed is filled with "observations" about GUI development in a slightly more general sense.

Once you do get around to posting something, feel free to open an issue / a PR about that!
