### ISSUE TITLE
Add a link to "So you want to write a GUI framework"

### ISSUE THREAD

**Issue by hammerandtongs** [areweguiyet/areweguiyet#75]
https://www.cmyr.net/blog/gui-framework-ingredients.html

Lays out a pretty broad but necessary set of items for a full featured gui framework.

Developers evaluating whether Rust is areweguiyet would do well to read this before they begin looking at Rust frameworks.

As a feature request for areweguiyet, what about a feature matrix based around this list?

**Comment by dxenonb** [comment]
Disposition to merge

**Comment by madsmtm** [comment]
Thanks for the link, I've put it on the site in https://github.com/areweguiyet/areweguiyet/pull/117.

I've moved the feature matrix suggestion to https://github.com/areweguiyet/areweguiyet/issues/21, since that's where we're discussing reworking tags/categories.
