### ISSUE TITLE
Add SixtyFPS

### ISSUE THREAD

**Issue by LeoniePhiline** [areweguiyet/areweguiyet#78]
Freshly announced and promising (IMHO):

- https://github.com/sixtyfpsui/sixtyfps
- https://sixtyfps.io/releases/0.1.1/docs/rust/sixtyfps/
- https://sixtyfps.io/blog/announcing-sixtyfps-0.1.html

**Comment by Nan1t** [comment]
But it already added. Anyway i'd recommend to remove CSS tag, beacause there is no CSS.

**Comment by dxenonb** [comment]
Has now been added, thank you! Closing. Next PR will remove CSS tag.
