### ISSUE TITLE
This repository needs new maintainers!

### ISSUE THREAD

**Issue by AaronErhardt** [areweguiyet/areweguiyet#84]
It's ok to discontinue projects, but this should never happen silently.

**Yet, this repository has been more or less unmaintained for over a year now.**

This means stale links and an outdated representation of what's the actual state of GUI development in Rust.
And to fork is not an option, as the domain is important, too, and a lot of resources already link here.

@pythoneer and @dxenonb what are your thoughts on this situation? If you are not willing to maintain this repository, please ask for others to help instead of letting this project become stale silently.

**Comment by dxenonb** [comment]
Thank you for addressing this - I agree.

If someone wants to maintain the _current_ site: Triaging the open issues/PRs would be very helpful. I would be happy to add someone as a maintainer if 

At the current moment, @pythoneer any opposition to:

- putting up a banner about this on the site?
- and adding a link to this issue in the readme?

I don't think the site in its current form hits anyone's needs superbly though (and that's my doing).

I think there could be very useful _future_ states of the site:

- An aggregator/crawler of say /r/rust gui threads (and other rust communities)
- Maybe a `awgy.toml` spec that can be used by a crawler to link blogs, tutorials, and examples
- Create a hub/forum for tutorials, history of gui development
- or winding it down and redirecting to other useful sources

Thanks for everyone's patience... all in all the current state is probably harmful to the community. I think everyone more or less knows what would be useful but

**Comment by Narann** [comment]
Thanks @dxenonb for your site. I can't help but just share I often come to it to see if there are any improvement. Hope you will find some help.

Keep the good work!

**Comment by rrrodzilla** [comment]
@dxenonb  what are your thoughts on using something like [Zola](https://www.getzola.org) as the renderer?  This would allow people to submit pull requests to markdown files and the site would deploy when the PRs are accepted? I would also be happy to assist with a more responsive design malversation the frontend if that is on your roadmap?

**Comment by stappersg** [comment]
> @dxenonb what are your thoughts on using something like [Zola](https://www.getzola.org) as the renderer? This would allow people to submit pull requests to markdown files and the site would deploy when the PRs are accepted? I can assist with setting that up if needed. I would also be happy to assist with a more responsive design on the frontend if that is on your roadmap?

I do like the _"allow people to submit requests"_ idea and hope that the _"can assist with setting that"_ offer is still valid (but fear it is expired).

**Comment by madsmtm** [comment]
Hello @dxenonb and @pythoneer, I'm the macOS and iOS developer of `winit`, and I think areweguiyet is a really good "hub" for projects like ours to link to.

I would be up for helping with maintenance for at least the next 6 months, if you want my help? Concretely, my order of operations would be:
- Merge the new content that has been submitted recently.
- Internal: Use toml instead of JSON, to allow people to easily edit the data.
- Work a bit on the CSS to make the experience on mobile better (content is a bit close to the edge of the screen, and hover effects when selecting tags works a bit funnily).
- Rework the current categories (`winit` as a category doesn't really make sense).
- Internal: Replace the custom site generator system with something like the suggested Zola, if possible. Though I'd still keep the "fetch data from crates.io" system.
- Perhaps link to communities (Element/Matrix, Discord, ...) where people can get help when starting out?

A few questions:
- What is the scope of the project? Does it make sense to link to tools for building application bundles like `.app` on macOS? This is decidedly not GUI development, but still likely to be relevant for everyone wanting to build an application with a GUI.
- Who owns the domain name currently, and how do we ensure that it stays up?

**Comment by dxenonb** [comment]
@pythoneer owns the domain name

@madsmtm I'd be happy to accept your offer, let me know if that is still open. I should be able to give you access later tonight, after which you can tackle this whenever you are next able & willing. 

With regards to your proposed items, they all sound good to me.

Regarding the data format, I think the most important change we want to look at is, each project gets its own JSON/toml file, to simplify merges/reading diffs.

Ive got to run but - I will try and drop a few more thoughts here this week regarding categories/site updates/scope of the site. Appreciate you reaching out about helping - I've certainly let the site languish. If you are still interested in tackling any of those items, I think everyone would be grateful!

**Comment by madsmtm** [comment]
Yeah I'm still open, no worries about the delay!

> simplify merges/reading diffs

I suspect that if we use `toml`, there won't really be a need for the `framework`/`news` CLI command that automatically adds a new project?

At least thinking like a flyby contributor that just want to add their project to the site, I'd much rather just edit a toml file by hand than have to run some CLI command that I don't necessarily trust, and that will take time to build on my machine.

But we can discuss the trade-offs when we get there.

**Comment by dxenonb** [comment]
Great, I've granted you write access @madsmtm!

> I suspect that if we use toml, there won't really be a need for the framework/news CLI command that automatically adds a new project?

I agree.

In general, I regret building the CLI: A contribution is only invalid if the JSON/TOML duplicates info that it can fetch. I think we could remove "use the CLI" as a contributor step, and instead just explain "your PR will fail if it duplicates fields (docs, repo) that are already available from crates.io, only specify these fields if your project is a framework, or not well represented by a single crate".

> What is the scope of the project? Does it make sense to link to tools for building application bundles like .app on macOS? This is decidedly not GUI development, but still likely to be relevant for everyone wanting to build an application with a GUI.

I think it does make sense to link to tools like you mention, but if the tool is not in Rust or for Rust, we might just want to include a link to official Microsoft/Apple/linux distro docs.

For content (GUI projects and tools), to me, all of the following are in scope:

 - These three categories answer the questions "How do I/Can I build an app right now? And what % of the stack is Rust?"
   - full lifecycle, batteries included frameworks: they help develop/package/update your app (e.g. Electron if it was Rust)
   - GUI frameworks: crate(s) that provide a full rendering/layout/interaction for some platform(s)
   - GUI bindings: crates that make it easy to use an existing non-Rust GUI framework
 - These three answer the questions "How do I <do UI stuff> in Rust?":
   - BYOUI (build/bring your own UI): crates that lack one or more major parts needed to build a functioning app, but could be key if you're building your own framework (e.g. webrender, HTML/CSS rendering related crates) or integrating in a complex existing application 
   - GUI-relevant crates: e.g. fontdue, wgpu, winit, stretch, bindings to low platform level APIs
   - GUI-relevant tools: tools that help ship/design/packaging Rust apps, but aren't linked in an executable

In scope for the repo: Given my inability to keep the site up to date, I'd prefer to reduce scope - possibly remove blogs/news and tags, don't build any new tooling that needs to be maintained (I previously dreamed of crawlers). But as lots of people have pointed out, UI is so complex and the current site so unhelpful, linking to examples or recipes would really elevate it.

I think grouping things in (roughly) the above categories could allow us to make the site more like arewegameyet.rs, while also addressing the needs of people who visit it.

I've updated #53 accordingly, if it is useful. I'll leave it up to you how you would like to track any ideas/plans - maybe a new tracking issue(s)?

**Comment by madsmtm** [comment]
Good points all around, I'll try to get some work done in my free time in the coming week

**Comment by madsmtm** [comment]
So I've done parts of the work, but due to internet issues, I'll possibly be unavailable for the next 20 days. Don't worry, I have not forgotten about this repo, there's still work needed before I'll feel satisfied!

**Comment by madsmtm** [comment]
I'll close this issue now, work is still ongoing on https://github.com/areweguiyet/areweguiyet/issues/21, but we can track that there.
