### ISSUE TITLE
List of crates not loaded

### ISSUE THREAD

**Issue by musikid** [areweguiyet/areweguiyet#88]
The list of crates is not loaded, and this error seems to be caused by the version returned by the CDN. It returns the version 3.2 instead of the version 2.6 before.

### Error

```
Uncaught TypeError: Vue.component is not a function
    <anonymous> https://www.areweguiyet.com/main.js:5
```

**Comment by pythoneer** [comment]
Thanks for this quick fix, which helped a lot. As mentioned in the PR itself i think instead of `@legacy` we should pin this to an exact version like `https://cdn.jsdelivr.net/npm/vue@2.6` what do you think @dxenonb
