### ISSUE TITLE
No automatic redirect to HTTPS

### ISSUE THREAD

**Issue by bkamphues** [areweguiyet/areweguiyet#93]
I was using the site recently and I noticed the webserver doesn't automatically redirect HTTP requests to HTTPS. Might be a good security feature to implement.

**Comment by madsmtm** [comment]
I think that's [an option you can enable in the repository](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site).

I don't have access to do so, so I'll assign @dxenonb to that.

**Comment by dxenonb** [comment]
Enabled, the redirect appears to be working now!
